### ISSUE TITLE
ETL1: Datahub -> Datahub 2

### ISSUE THREAD

**Issue by Hobbesball** [VlaamseKunstcollectie/Imagehub-Fixes#1]
This issue is made to give the assignment for the creation of ETL1, and to track its progress. This ETL can be either a Perl Catmandu fix or a PHP script. 

**Summary**: 200 LIDO files from the Datahub need to be extracted, enriched, and translated with the extra metadata in CSV files, so we can research how to develop data models for a IIIF implementation in the Arthub with ideal metadata files. 

**Acceptance criteria:**
- LIDO files listed in the 200LIDOfiles.csv are automatically extracted from the live Datahub OAI-PMH and uploaded to the Datahub 2 on our VPS.

- every metadata file has a <descriptivemetadata xml:lang="nl"> section and a <descriptivemetadata xml:lang="en"> wrapper.
- Both the <descriptivemetadata xml:lang="nl"> wrapper and the <descriptivemetadata xml:lang="en"> only contain maximum 1 object title, which is in the language that the wrapper defines if that language or translation is available in the 200titles.csv
- Both the <descriptivemetadata xml:lang="nl"> wrapper and the <descriptivemetadata xml:lang="en"> only contain exactly 1 object description, which is in the language that the wrapper defines and has been copied from 200descriptions.csv
- Both the <descriptivemetadata xml:lang="nl"> wrapper and the <descriptivemetadata xml:lang="en"> only contain exactly 1 object institution, which is in the language that the wrapper defines and has been copied from legalbodynames.csv
- Both the <descriptivemetadata xml:lang="nl"> wrapper and the <descriptivemetadata xml:lang="en"> only contain 1 or more object creation periods, which are in the language that the wrapper defines and have been copied from periodtranslations.csv

- if there is only 1 image (=resource) associated with a LIDO file, it is described in the <administrativemetadata> wrapper with 1 resourceID. 
- if there are multiple images (=resources) associated with a LIDO file, they are all described in the <administrativeMetadata> wrapper, each with their own resourceID. 
- the copyright status of each resource is describe in the <administrativemetadata> wrapper in the rightsType field. 

- If a LIDO file is related to other LIDO files, those relations are described in the <descriptivemetadata> wrappers for both languages, in the <relatedWorksWrap>.

**nice to have**
- if it is possible to connect to the Getty AAT thesaurus to automatically translate terms that have now been extracted in Dutch (e.g. objectWorkType) and put them in the <descriptiveMetadata xml:lang="en"> wrapper, that would be nice, but is not a requirement for ETL1. 

**Sources of info**
- please consult the README of this repo for more info on what each XML example shows
- please consult the [wiki page on the CSV files](https://github.com/VlaamseKunstcollectie/Imagehub-Fixes/wiki/csv-files) for more information on Xpaths, the logic the ETL needs to handle, and which info can be found where in which sheet. 

I hope I gave all the info you need, if there's anything else I can help with for this ETL, let me know!

**Comment by Kitania** [comment]
The CSV files containing titles and descriptions appeared to have inconsistent formatting, several escape characters seemed to be in the wrong place and not all rows had the same column count. Please see #2 for a fix for the issues.

**Comment by Kitania** [comment]
There are only 199 LIDO files in 200LIDOfiles.csv. Also, 6 LIDO records appear to be missing from the live Datahub:

> No matching identifier oai:datahub.vlaamsekunstcollectie.be:kunstenenerfgoed.be:BK_1869
No matching identifier oai:datahub.vlaamsekunstcollectie.be:kunstenenerfgoed.be:6698
No matching identifier oai:datahub.vlaamsekunstcollectie.be:kunstenenerfgoed.be:6696
No matching identifier oai:datahub.vlaamsekunstcollectie.be:kunstenenerfgoed.be:BKT_007
No matching identifier oai:datahub.vlaamsekunstcollectie.be:kunstenenerfgoed.be:784_B
No matching identifier oai:datahub.vlaamsekunstcollectie.be:collectievlaamsegemeenschap.be:2251

**Comment by Hobbesball** [comment]
Done! Closing this task.
